//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShop1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GardenShop1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj u nabavku.
        /// </summary>
        internal static string addProcurement {
            get {
                return ResourceManager.GetString("addProcurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj na račun.
        /// </summary>
        internal static string addToBill {
            get {
                return ResourceManager.GetString("addToBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite količinu:.
        /// </summary>
        internal static string enterQuantity {
            get {
                return ResourceManager.GetString("enterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime i lozinku..
        /// </summary>
        internal static string enterUsernameAndPassword {
            get {
                return ResourceManager.GetString("enterUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške, pokušajte ponovo..
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postoji proizvod sa navedenom šifrom..
        /// </summary>
        internal static string existsProduct {
            get {
                return ResourceManager.GetString("existsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo vas da popunite sva polja..
        /// </summary>
        internal static string fillFields {
            get {
                return ResourceManager.GetString("fillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hidden {
            get {
                object obj = ResourceManager.GetObject("hidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj računa.
        /// </summary>
        internal static string idBill {
            get {
                return ResourceManager.GetString("idBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj nabavke.
        /// </summary>
        internal static string idProcurement {
            get {
                return ResourceManager.GetString("idProcurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredencijalni nisu ispravni..
        /// </summary>
        internal static string incorrectCredentials {
            get {
                return ResourceManager.GetString("incorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovaj nalog je deaktiviran..
        /// </summary>
        internal static string notActive {
            get {
                return ResourceManager.GetString("notActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos količine.
        /// </summary>
        internal static string quantityEntry {
            get {
                return ResourceManager.GetString("quantityEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni nalog.
        /// </summary>
        internal static string removeAccount {
            get {
                return ResourceManager.GetString("removeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite da uklonite odabrani nalog?.
        /// </summary>
        internal static string removeAccountQuestion {
            get {
                return ResourceManager.GetString("removeAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni proizvod.
        /// </summary>
        internal static string removeArticle {
            get {
                return ResourceManager.GetString("removeArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite ukloniti proizvod?.
        /// </summary>
        internal static string removeArticleQuestion {
            get {
                return ResourceManager.GetString("removeArticleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema dovoljno proizvoda na stanju..
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno.
        /// </summary>
        internal static string successful {
            get {
                return ResourceManager.GetString("successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiranje je uspješno izvršeno..
        /// </summary>
        internal static string successfulCreate {
            get {
                return ResourceManager.GetString("successfulCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvod je uspešno uklonjen..
        /// </summary>
        internal static string successfulRemove {
            get {
                return ResourceManager.GetString("successfulRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nalog je uspjesno uklonjen..
        /// </summary>
        internal static string successfulRemoveAccount {
            get {
                return ResourceManager.GetString("successfulRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno uklanjanje.
        /// </summary>
        internal static string successfulRmv {
            get {
                return ResourceManager.GetString("successfulRmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešna izmena.
        /// </summary>
        internal static string successfulUpd {
            get {
                return ResourceManager.GetString("successfulUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci su uspešno izmenjeni..
        /// </summary>
        internal static string successfulUpdate {
            get {
                return ResourceManager.GetString("successfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navedeno korisničko ime je zauzeto..
        /// </summary>
        internal static string takenUsername {
            get {
                return ResourceManager.GetString("takenUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupna cijena.
        /// </summary>
        internal static string totalPrice {
            get {
                return ResourceManager.GetString("totalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokušaj ponovo.
        /// </summary>
        internal static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeste li sigurni da želite izmijeniti podatke?.
        /// </summary>
        internal static string updateQuestion {
            get {
                return ResourceManager.GetString("updateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće učitati sliku..
        /// </summary>
        internal static string uploadPicture {
            get {
                return ResourceManager.GetString("uploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
