insert into user(name, surname, username, password, phoneNumber, isAdmin, Active, Language, Theme) values('Danica', 'Vuković', 'admin', 'admin', '066/555-444', '1', '1', '1','2');
insert into user(name, surname, username, password, phoneNumber, isAdmin, Active, Language, Theme) values('Marija', 'Marković', 'marija', 'marija', '066/085-498', '0', '1', '1','1');
insert into user(name, surname, username, password, phoneNumber, isAdmin, Active, Language, Theme) values('Janko', 'Janković', 'janko', 'janko', '066/235-994', '0', '1', '2','3');
insert into user(name, surname, username, password, phoneNumber, isAdmin, Active, Language, Theme) values('Ana', 'Popović', 'ana', 'ana123', '066/125-834', '0', '1', '1','4');
insert into user(name, surname, username, password, phoneNumber, isAdmin, Active, Language, Theme) values('Nikola', 'Nikolic', 'nikola', 'nikola123', '066/565-455', '0', '1', '1','2');

insert into category(name) values ('Ruže');
insert into category(name) values ('Ukrasno žbunje');
insert into category(name) values ('Četinari');
insert into category(name) values ('Živa ograda');
insert into category(name) values ('Lukovice');
insert into category(name) values ('Alati i oprema');

insert into procurer(name, surname, phoneNumber) values ('Marko', 'Marković' , '066/555-333');
insert into procurer(name, surname, phoneNumber) values ('Sandra', 'Savić' , '066/995-373');
insert into procurer(name, surname, phoneNumber) values ('Zoran', 'Stanković' , '066/987-654');
insert into procurer(name, surname, phoneNumber) values ('Ivan', 'Dragović' , '066/935-434');

insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1101', 'Ruža Nikolo Paganini','ruzaNikoloPaganini.jpg','Dekorativna i efektna, jedna od najljepših crvenih čajevki.', '1', '100', '4.00','2.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1102', 'Ruža Tamora','ruzaTamora.jpg','Engleska ruza Tamora je ruža svijetle boje kajsije krupnih, kovrdžavih cvjetova izuzetnog mirisa. Ruža izuzetno velikih cvjetova prepuna brojnih latica. Cvjeta od maja do oktobra, zahtjeva puno sunca.', '1', '100', '5.80','1.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1103', 'Ruža Renaisssance','ruzaRenaisssance.jpg','Šatirana, dvobojna ljepotica i mnogocvjetnica. Raste od 80-100cm i cvjeta dugo u više navrata. Prilično je otporna na bolesti ruža, a zbog specifičnog izgleda je nezaobilazna u vrtu.', '1', '100', '3.00','1.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1104', 'Ruža Friesia','ruzaFriesia.jpg','Mnogocvjetnica čiste žute boje. Ruža ima čvrst i dug pupoljak, pa je dobar izbor i za rezani cvijet. Cvjeta od maja do oktobra i prilično je otporna na bolesti ruža.', '1', '100', '5.50','2.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1201', 'Fotinija Fraseri Carre Rouge','ukrasnoZbunjeFotinijaFraseriCarreRouge.jpg','Ova vrsta Fotinije je zimzeleni žbun, koji ima manje listove od Red Robin vrste. Listovi su u osnovu tamno-zeleni, ali mladi listovi su izrazito crvene i upečatljive boje. Pojavljuju se dva puta godišnje: u rano proljeće i kasno ljeto. Fotinija koja ne raste visoko 2-2,5m i voli sunčane i polusunčane pozicije.', '2', '100', '13.50','5.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1202', 'Kalistemon','ukrasnoZbunjeKalistemon.jpg','Cvijet Kalistemona jake crvene boje i oblika koji podsjeća na četku za flaše. Zbog izgleda cvijeta zovu ga i četkovac. U saksiji deluje vrlo dekorativan i atraktivan.', '2', '100', '8.50','3.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1203', 'Oranz Berberis','ukrasnoZbunjeOranzBerberis.jpg','Ovo je prelijepa sorta zimzelenog Berberisa sa grozdovima narandžasto - žutog cvijeta koji u proljeće kao plamen okiti biljku.', '2', '100', '7.50','4.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1204', 'Viburnum Davidii Zimzelena Udika','ukrasnoZbunjeViburnumDavidiiZimzelenaUdika.jpg','Pored sitnih krem-bijelih cvjetova, ova Udika ima izrazito upadljive, sjajne i duge zimzelene listove. Ova vrsta ne raste visoko 1,5-2m, isto tako i u širinu. Zato je pogodna za sadnju u većim grupama gdje postiže najbolji efekat.', '2', '100', '10.00','6.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1301', 'Duglazija-Pseudotsuga menziesii','cetinariDuglazija.jpg','Nježne, meke četine daju joj specifičan izgled. Pored četina, krase je i šišarke duge do 10cm. Odlikuje je brzi rast i dobro podnošenje gradskih uslova.', '3', '100', '15.00','9.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1302', 'Patuljasti bor-Pinus mugo','cetinariPatuljastiBorPinusMugo.jpg','Atraktivan i uvijek popularan ovaj patuljasti bor idealan je za male vrtove, žardinjere, krovne vrtove, velike terase, padine.', '3', '100', '10.00','6.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1303', 'Jelka-Smrča','cetinariJelkaSmrca.jpg','Mirišljavi četinar najviše korišćen kao Novogodišnja jelka. Odlično podnosi orezivanje i može se formirati kao živa ograda ili gusta jelka za kićenje. Imajte pravu jelku u svom dvorištu.', '3', '100', '13.00','9.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1304', 'Crni bor','cetinariCrniBor.jpg','Crni bor je graciozan četinar čija krošnja je kupasta do kišobranaste i zbog toga je jako interesantan. Ovaj bor uspijeva u jako oskudnim uslovima, što govori o njegovoj otpornosti. Ima izuzetno jak korijen, pa se koristi i za pošumljavanje nagiba i kosih terena. Šišarke kod bora se pojavljuju u kasnu jesen i na zimu i ostaju na granama kao dekoracija.', '3', '100', '16.00','10.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1401', 'Spirea - zlatna princeza','zivaOgradaSpireaZlatnaPrinceza.jpg','Jedna od najljepših Spirea, kompaktna, gusta i listom vrlo upadljiva. Može se saditi pojedinačno ili u grupama i lejama kada posebno izgleda efektno.', '4', '100', '6.50','4.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1402', 'Lejlandski čempres zeleni','zivaOgradaLejlandskiCempresZeleni.jpg','Otporan četinar brzog rasta koji se najviše koristi za formiranje gustih i visokih živih ograda. Živa ograda ne mora biti široka zbog mogućnosti orezivanja koju ova biljka dobro podnosi. Atraktivan i za pojedinačnu sadnju zbog mogućnosti oblikovanja u spiral ili drugi željeni oblik.', '4', '100', '7.00','4.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable) values('1403', 'Cvetna lovor višnja','zivaOgradaCvetnaLovorVisnja.jpg','Za razliku od ostalih lovor višnji ova vrsta posebno lijepo i upadljivo cvjeta. Ova vrsta ima bele cvjetove koji cvjetaju u maju i junu. Vrlo izdržljiva i podnosi i zasjenčene terene.', '4', '100', '8.00','4.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1404', 'Lovor višnja','zivaOgradaLovorVisnja.jpg','Ako vam treba jaka, široka i visoka ograda to je lovor višnja. Koristi se za šišane i slobodno rastuće živice. Ima više sorti.', '4', '100', '6.50','3.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1501', 'Lale Lily Mix','lukoviceLaleLilyMix.jpg','Elegantne i raznobojne lale, sa specifičnim špicastim laticama ukrasiće Vaše ivice travnjaka, staza i kamenjara, u grupama kako su najljepše. Zajedno sa jednobojnim i lukovicama nižeg rasta dobićete potpunu kompoziciju.', '5', '100', '6.00','4.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1502', 'Ljiljan narandžasti Orange County','lukoviceJanNarandzastiOrangeCounty.jpg','Kada pomislite na biljku ljiljan, pomislite na narandžasti ljiljan, baš ovaj! Fenomenalna boja za sve smjele baštovane, ukrasiće Vaše bašte i pokupiti sve poglede, a ako poželite da ga zadržite samo za sebe ljiljani su odlični za rezani cvijet.', '5', '100', '8.50','5.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1503', 'Lala Fringed Bresta','lukoviceLalaFringedBresta.jpg','Lala čiji cvijet izgleda kao da je posut injem. Poslije snijega i zime, obradovaće vas boje ove specifične i svakako nesvakidašnje lale. Pogodna je za sadnju u saksijama i vazama, kao i u vašim vrtovima.', '5', '100', '7.50','5.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1504', 'Narcis dupli Rip Van Winkle','lukoviceNarcisDupliRipVanWinkle.jpg','Patuljasti narcis koji ima neobične latice, zelenkasto žute boje koji izgledaju vrlo različito od drugih narcisa. Njegova kraća visina čini ga idealnim za sadnju na prednjoj strani. Lijepo bi se uklopio sa lalama jačih boja.', '5', '100', '7.00','5.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1601', 'Makaze za orezivanje KEW','alatiMakazeZaOrezivanjeKew.jpg','Makaze sa sječivima od visokog ugljeničnog čelika za snagu i trajnu oštrinu sa podesivim zatezanjem.', '6', '50', '50.00','35.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1602', 'Baštenski set','alatiBastenskiSet.jpg','Set od tri neophodna ručna alata za baštu.', '6', '100', '80.00','50.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1603', 'Testera preklopna za orezivanje - mala','alatiTesteraPreklopnaZaOrezivanjeMala.jpg','Testera pogodna za sječenje žbunja i lagano orezivanje drveća.', '6', '100', '60.00','40.00', '1');
insert into article(idArticle, Name, Picture, Description,Category_idCategory, AvailableQuantity,SalePrice,ProcurementPrice, isAvailable)values('1604', 'alatiGrabulje3u1','alatiGrabulje3u1.jpg','Vrlo praktične grabulje lišća pogodne za održavanje vaše bašte.', '6', '100', '90.00','60.00', '1');

call addProcurement('2024-01-18 15:13:00', 3, 1, 1101, 1602, 1201);
call addProcurement('2023-06-19 14:12:00', 2, 2, 1204, 1504, 1501);
call addProcurement('2024-01-03 16:14:00', 3, 3, 1403, 1104, 1401);
call addProcurement('2024-01-09 13:30:00', 4, 1, 1103, 1101, 1302);

call addBill('2024-01-10 14:15:00', 2, 1101, 1202, 1301);
call addBill('2024-01-19 17:19:00', 3, 1204, 1304, 1501);
call addBill('2024-01-26 13:40:00', 4, 1303, 1104, 1601);
call addBill('2024-01-16 11:56:00', 4, 1102, 1101, 1301);